package org.loomsip.dialog;

/** Reason recorded when a Dialog reaches Terminated. */
public enum DialogTerminationReason {
    /** Protocol or application requested termination. */
    EXPLICIT,
    /** A non-success final response ended an Early Dialog. */
    NON_SUCCESS_FINAL_RESPONSE,
    /** The dialog-forming INVITE transaction ended with an Early Dialog remaining. */
    INVITE_TRANSACTION_TERMINATED,
    /** A locally generated BYE was accepted by the Non-INVITE transaction layer. */
    LOCAL_BYE,
    /** A remote BYE passed Dialog identity and CSeq validation. */
    REMOTE_BYE,
    /** Session refresher missed the negotiated RFC 4028 deadline. */
    SESSION_EXPIRED,
    /** An automatic RFC 4028 refresh transaction failed. */
    SESSION_REFRESH_FAILED,
    /** Owning Dialog manager is closing. */
    MANAGER_SHUTDOWN,
    /** Mailbox or execution infrastructure failed. */
    INFRASTRUCTURE_FAILURE
}
